import fs from "node:fs";
import path from "node:path";

const projectRoot = process.cwd();
const distDir = path.join(projectRoot, "dist");
const outputFile = path.join(distDir, "Code.js");
const manifestSource = path.join(projectRoot, "appsscript.json");
const manifestTarget = path.join(distDir, "appsscript.json");

const buildOrder = [
  "src/config.ts",
  "src/infra/json.ts",
  "src/infra/ids.ts",
  "src/infra/dates.ts",
  "src/infra/slug.ts",
  "src/infra/sheets.ts",
  "src/domain/validation.ts",
  "src/domain/wineLog.ts",
  "src/domain/wineSession.ts",
  "src/domain/userProfile.ts",
  "src/tests/fixtures.ts",
  "src/api/handlers.ts",
  "src/api/router.ts",
  "src/Code.ts",
];

const banner = [
  "// Generated by scripts/build.mjs",
  "// Source of truth lives in /src",
  "",
].join("\n");

fs.mkdirSync(distDir, { recursive: true });

const output = banner +
  buildOrder
    .map((relativePath) => {
      const fullPath = path.join(projectRoot, relativePath);
      const content = fs.readFileSync(fullPath, "utf8").trimEnd();
      return `// ---- ${relativePath} ----\n${content}\n`;
    })
    .join("\n");

fs.writeFileSync(outputFile, output, "utf8");
fs.copyFileSync(manifestSource, manifestTarget);

console.log(`Built ${path.relative(projectRoot, outputFile)}`);
