var APP_CONFIG = {
  version: "3.0.0",
  timezone: "Asia/Tokyo",
  defaultProfileKey: "default",
  spreadsheetIdProperty: "SPREADSHEET_ID",
  apiKeyProperty: "API_KEY",
  sheetNames: {
    wineLog: "WineLog",
    wineSession: "WineSession",
    userProfile: "UserProfile",
  },
  allowedWineTypes: ["Red", "White", "Rose", "Sparkling", "Orange", "Cider", "Sake", "Other"],
  wineLogColumns: [
    "record_id",
    "session_key",
    "date",
    "opened_on",
    "open_day",
    "type",
    "name",
    "vintage",
    "producer",
    "country",
    "region",
    "sub_region",
    "location",
    "grape_varieties_json",
    "aroma_json",
    "paired_dishes_json",
    "ratings_color",
    "ratings_aroma",
    "ratings_tannin",
    "ratings_acidity",
    "ratings_fruit",
    "overall_score_5",
    "overall_grade",
    "scene_people",
    "scene_style",
    "scene_mood",
    "repurchase_intent",
    "tags_json",
    "overall_comment",
    "meta_inferred_fields_json",
    "meta_notes",
    "summary_jp",
    "raw_json",
    "created_at",
    "updated_at",
    "deleted_flag",
  ],
  wineSessionColumns: [
    "session_key",
    "wine_name",
    "opened_on",
    "location",
    "type",
    "producer",
    "country",
    "region",
    "sub_region",
    "vintage",
    "record_ids_json",
    "latest_record_id",
    "latest_open_day",
    "days_logged",
    "best_overall_score_5",
    "latest_overall_score_5",
    "best_pairing",
    "final_impression",
    "repurchase_intent",
    "created_at",
    "updated_at",
  ],
  userProfileColumns: [
    "profile_key",
    "favorite_types_json",
    "preferred_grapes_json",
    "rating_pattern_json",
    "best_pairings_json",
    "avoid_patterns_json",
    "top_regions_json",
    "top_producers_json",
    "summary",
    "source_record_count",
    "updated_at",
  ],
  columnWidths: {
    WineLog: {
      1: 180,
      2: 240,
      7: 220,
      14: 260,
      15: 260,
      16: 320,
      28: 240,
      29: 360,
      30: 240,
      32: 360,
      33: 600,
    },
    WineSession: {
      1: 240,
      2: 260,
      11: 320,
      17: 220,
      18: 360,
    },
    UserProfile: {
      2: 260,
      3: 260,
      4: 220,
      5: 260,
      6: 260,
      7: 260,
      8: 260,
      9: 420,
    },
  },
};
